#!/bin/sh
. ./parameter.cfg
rm -rf .aws-sam
rm -rf ./lib/python/*
mkdir -p lib/python

# Boxモジュールをコピー
cp -r Box lib/python

# Dockerコンテナ内でpip installを実行（Python 3.12、Amazon Linux 2023、x86_64互換）
docker run --rm \
    --platform linux/amd64 \
    -v "$(pwd)":/var/task \
    -w /var/task \
    --entrypoint /bin/bash \
    public.ecr.aws/lambda/python:3.12 \
    -c "pip install -r requirements.txt -t lib/python --upgrade --no-cache-dir"

sam build
cd .aws-sam/build
aws cloudformation package \
    --region $REGION \
    --template-file template.yaml \
    --s3-prefix $PROJECT_NAME \
    --s3-bucket $S3_BUCKET \
    --output-template-file packaged.yaml
aws cloudformation deploy \
    --stack-name $PROJECT_NAME \
    --template-file packaged.yaml \
    --region $REGION \
    --capabilities CAPABILITY_NAMED_IAM  \
    --s3-bucket $S3_BUCKET \
    --s3-prefix $PROJECT_NAME \
