AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BoxSDK:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Box
      Description: Box SDK
      ContentUri: lib
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.6
